// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: mnr/gtfs-realtime-MNR.proto

package mnr

import (
	transit_realtime "github.com/errornil/mta/v3/proto/transit_realtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MnrStopTimeUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Track       *string `protobuf:"bytes,1,opt,name=track" json:"track,omitempty"` //can add additional fields here without having to //extend StopTimeUpdate again
	TrainStatus *string `protobuf:"bytes,2,opt,name=trainStatus" json:"trainStatus,omitempty"`
}

func (x *MnrStopTimeUpdate) Reset() {
	*x = MnrStopTimeUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mnr_gtfs_realtime_MNR_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MnrStopTimeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MnrStopTimeUpdate) ProtoMessage() {}

func (x *MnrStopTimeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mnr_gtfs_realtime_MNR_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MnrStopTimeUpdate.ProtoReflect.Descriptor instead.
func (*MnrStopTimeUpdate) Descriptor() ([]byte, []int) {
	return file_mnr_gtfs_realtime_MNR_proto_rawDescGZIP(), []int{0}
}

func (x *MnrStopTimeUpdate) GetTrack() string {
	if x != nil && x.Track != nil {
		return *x.Track
	}
	return ""
}

func (x *MnrStopTimeUpdate) GetTrainStatus() string {
	if x != nil && x.TrainStatus != nil {
		return *x.TrainStatus
	}
	return ""
}

var file_mnr_gtfs_realtime_MNR_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*transit_realtime.TripUpdate_StopTimeUpdate)(nil),
		ExtensionType: (*MnrStopTimeUpdate)(nil),
		Field:         1005,
		Name:          "mnr.mnr_stop_time_update",
		Tag:           "bytes,1005,opt,name=mnr_stop_time_update",
		Filename:      "mnr/gtfs-realtime-MNR.proto",
	},
}

// Extension fields to transit_realtime.TripUpdate_StopTimeUpdate.
var (
	// optional mnr.MnrStopTimeUpdate mnr_stop_time_update = 1005;
	E_MnrStopTimeUpdate = &file_mnr_gtfs_realtime_MNR_proto_extTypes[0]
)

var File_mnr_gtfs_realtime_MNR_proto protoreflect.FileDescriptor

var file_mnr_gtfs_realtime_MNR_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x6e, 0x72, 0x2f, 0x67, 0x74, 0x66, 0x73, 0x2d, 0x72, 0x65, 0x61, 0x6c, 0x74,
	0x69, 0x6d, 0x65, 0x2d, 0x4d, 0x4e, 0x52, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d,
	0x6e, 0x72, 0x1a, 0x13, 0x67, 0x74, 0x66, 0x73, 0x2d, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x11, 0x4d, 0x6e, 0x72, 0x53, 0x74,
	0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x3a, 0x75, 0x0a, 0x14, 0x6d, 0x6e, 0x72, 0x5f, 0x73, 0x74, 0x6f, 0x70,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x2e, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x54, 0x72, 0x69, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x54,
	0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0xed, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6d, 0x6e, 0x72, 0x2e, 0x4d, 0x6e, 0x72, 0x53, 0x74, 0x6f, 0x70, 0x54, 0x69,
	0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x11, 0x6d, 0x6e, 0x72, 0x53, 0x74, 0x6f,
	0x70, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x47, 0x0a, 0x1f, 0x63,
	0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69,
	0x74, 0x2e, 0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x6d, 0x6e, 0x72, 0x5a, 0x24,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x6e, 0x69, 0x6c, 0x2f, 0x6d, 0x74, 0x61, 0x2f, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x6e, 0x72,
}

var (
	file_mnr_gtfs_realtime_MNR_proto_rawDescOnce sync.Once
	file_mnr_gtfs_realtime_MNR_proto_rawDescData = file_mnr_gtfs_realtime_MNR_proto_rawDesc
)

func file_mnr_gtfs_realtime_MNR_proto_rawDescGZIP() []byte {
	file_mnr_gtfs_realtime_MNR_proto_rawDescOnce.Do(func() {
		file_mnr_gtfs_realtime_MNR_proto_rawDescData = protoimpl.X.CompressGZIP(file_mnr_gtfs_realtime_MNR_proto_rawDescData)
	})
	return file_mnr_gtfs_realtime_MNR_proto_rawDescData
}

var file_mnr_gtfs_realtime_MNR_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mnr_gtfs_realtime_MNR_proto_goTypes = []interface{}{
	(*MnrStopTimeUpdate)(nil),                          // 0: mnr.MnrStopTimeUpdate
	(*transit_realtime.TripUpdate_StopTimeUpdate)(nil), // 1: transit_realtime.TripUpdate.StopTimeUpdate
}
var file_mnr_gtfs_realtime_MNR_proto_depIdxs = []int32{
	1, // 0: mnr.mnr_stop_time_update:extendee -> transit_realtime.TripUpdate.StopTimeUpdate
	0, // 1: mnr.mnr_stop_time_update:type_name -> mnr.MnrStopTimeUpdate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mnr_gtfs_realtime_MNR_proto_init() }
func file_mnr_gtfs_realtime_MNR_proto_init() {
	if File_mnr_gtfs_realtime_MNR_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mnr_gtfs_realtime_MNR_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MnrStopTimeUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mnr_gtfs_realtime_MNR_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_mnr_gtfs_realtime_MNR_proto_goTypes,
		DependencyIndexes: file_mnr_gtfs_realtime_MNR_proto_depIdxs,
		MessageInfos:      file_mnr_gtfs_realtime_MNR_proto_msgTypes,
		ExtensionInfos:    file_mnr_gtfs_realtime_MNR_proto_extTypes,
	}.Build()
	File_mnr_gtfs_realtime_MNR_proto = out.File
	file_mnr_gtfs_realtime_MNR_proto_rawDesc = nil
	file_mnr_gtfs_realtime_MNR_proto_goTypes = nil
	file_mnr_gtfs_realtime_MNR_proto_depIdxs = nil
}
