name: golangci-lint

on:
  push:
    branches:
      - main
      - v3
  pull_request:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
